spring:
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        #format_sql: true
        #use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://210.114.225.73:3306/apt4u
    username: apt4u_user
    password: rkdengml@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  urldata:
    api: api

server:
  port: 8082